name: CICD
on:
    push:
        branches:
            - deploy-to-ec2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD  }}
            - name: BuildDocker Image
              run: docker build -t mandaartamboli/react-app .
            - name: publish image to docker hub
              run: docker push mandaartamboli/react-app:latest

    deploy:
      needs: build
      runs-on: [self-hosted, aws-ec2-runner]
      steps:
      - name: pULL IMAGE FROM DOCKER HUB
        run: DOCKER PULL mandaartamboli/react-app:latest
      - name: Deleteold Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name  reactContainer mandaartamboli/react-app:latest